# Generated by Django 5.1.1 on 2024-10-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientDomain',
            new_name='Domain',
        ),
    ]
