# Generated by Django 5.1.1 on 2024-10-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_clientdomain_domain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domain',
            new_name='ClientDomain',
        ),
    ]
